# Generated by Django 4.2 on 2023-05-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(through="courses.CourseTag", to="courses.tag"),
        ),
    ]
