# Generated by Django 4.2 on 2023-05-05 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="dislikes",
            field=models.ManyToManyField(
                related_name="disliked_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="enrollment_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="is_package",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="site",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="url",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="series",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="series",
            name="subtitle",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
